#ifndef __UI_H
#define __UI_H

/* Includes ------------------------------------------------------------------*/
#include "adc_sample.h"
#include "button.h"
#include "config_flash.h"
#include "common.h"
#include "datetime.h"
#include "di.h"
#include "irrigation.h"
#include "lcd.h"
#include "main.h"
#include "version.h"
#include "weather.h"

/* Functions -----------------------------------------------------------------*/
void ui_init (void);
void ui_1s_tick (void);
void ui_task(void);

/* Exported Variables --------------------------------------------------------*/
extern uint8_t User_Logged_In;

/* Defines -------------------------------------------------------------------*/
#define T_WELCOME     10 //s
#define T_LOW_POWER	  50 //s      Cambiar por valor más alto, solo pruebas
#define UI_TIME       250//ms

#define PASS_SIZE			8
#define NAME_SIZE     16

#define RECIPE_1      1
#define RECIPE_2      2

/* Users ---------------------------------------------------------------------*/
enum {
  USR_NONE,
  USR_OP1,
  USR_OP2,
  USR_SUP1,
  USR_SUP2,
  USR_MASTER,
  USR_MB
};

// Menus
enum {
  MS_START,
  MS_WEATHER, 
  MS_RECIPE_1,
  MS_RECIPE_2, 
  MS_SYS, 
  MS_LAST
};

enum {
  M_USR_OP1,
  M_USR_OP2,
  M_USR_SUP1,
  M_USR_SUP2,
  M_USR_MASTER
};

/* States --------------------------------------------------------------------*/
enum{
  UI_MAIN_BUTTON_A, UI_MAIN_BUTTON_B,

  UI_USER_0, UI_USER_1, UI_USER_BUTTON_A, UI_USER_BUTTON_B,
  UI_LOGIN_0, UI_LOGIN_1, UI_LOGIN_BUTTON_A, UI_LOGIN_BUTTON_B,
  
  UI_ENTER_SCREEN_STOPPED, UI_ENTER_BUTTON_STOPPED_A, UI_ENTER_BUTTON_STOPPED_B,
//  UI_ENTER_SCREEN_RUNNING, UI_ENTER_BUTTON_RUNNING_A, UI_ENTER_BUTTON_RUNNING_B,

  WEATHER_T_H_0, WEATHER_T_H_1, WEATHER_T_H_BUTTON_A, WEATHER_T_H_BUTTON_B,
  WEATHER_T_L_0, WEATHER_T_L_1, WEATHER_T_L_BUTTON_A, WEATHER_T_L_BUTTON_B,
  WEATHER_H_H_0, WEATHER_H_H_1, WEATHER_H_H_BUTTON_A, WEATHER_H_H_BUTTON_B,
  WEATHER_H_L_0, WEATHER_H_L_1, WEATHER_H_L_BUTTON_A, WEATHER_H_L_BUTTON_B, 
  WEATHER_END,
  
  RECIPE_1_NAME_0, RECIPE_1_NAME_1, RECIPE_1_NAME_BUTTON_A, RECIPE_1_NAME_BUTTON_B,
  RECIPE_1_GROW_0, RECIPE_1_GROW_1, RECIPE_1_GROW_BUTTON_A, RECIPE_1_GROW_BUTTON_B,
  RECIPE_1_SUNRISE_0, RECIPE_1_SUNRISE_1, RECIPE_1_SUNRISE_BUTTON_A, RECIPE_1_SUNRISE_BUTTON_B,
  RECIPE_1_SUNSET_0, RECIPE_1_SUNSET_1, RECIPE_1_SUNSET_BUTTON_A, RECIPE_1_SUNSET_BUTTON_B,
  RECIPE_1_FLOW_D_0, RECIPE_1_FLOW_D_1, RECIPE_1_FLOW_D_BUTTON_A, RECIPE_1_FLOW_D_BUTTON_B,
  RECIPE_1_NOFLOW_D_0, RECIPE_1_NOFLOW_D_1, RECIPE_1_NOFLOW_D_BUTTON_A, RECIPE_1_NOFLOW_D_BUTTON_B,
  RECIPE_1_FLOW_N_0, RECIPE_1_FLOW_N_1, RECIPE_1_FLOW_N_BUTTON_A, RECIPE_1_FLOW_N_BUTTON_B,
  RECIPE_1_NOFLOW_N_0, RECIPE_1_NOFLOW_N_1, RECIPE_1_NOFLOW_N_BUTTON_A, RECIPE_1_NOFLOW_N_BUTTON_B,
  RECIPE_1_EC_H_0, RECIPE_1_EC_H_1, RECIPE_1_EC_H_BUTTON_A, RECIPE_1_EC_H_BUTTON_B,
  RECIPE_1_EC_L_0, RECIPE_1_EC_L_1, RECIPE_1_EC_L_BUTTON_A, RECIPE_1_EC_L_BUTTON_B,  
  RECIPE_1_PH_H_0, RECIPE_1_PH_H_1, RECIPE_1_PH_H_BUTTON_A, RECIPE_1_PH_H_BUTTON_B,
  RECIPE_1_PH_L_0, RECIPE_1_PH_L_1, RECIPE_1_PH_L_BUTTON_A, RECIPE_1_PH_L_BUTTON_B,   
  RECIPE_1_END,
  
  RECIPE_2_NAME_0, RECIPE_2_NAME_1, RECIPE_2_NAME_BUTTON_A, RECIPE_2_NAME_BUTTON_B,
  RECIPE_2_GROW_0, RECIPE_2_GROW_1, RECIPE_2_GROW_BUTTON_A, RECIPE_2_GROW_BUTTON_B,   
  RECIPE_2_SUNRISE_0, RECIPE_2_SUNRISE_1, RECIPE_2_SUNRISE_BUTTON_A, RECIPE_2_SUNRISE_BUTTON_B,
  RECIPE_2_SUNSET_0, RECIPE_2_SUNSET_1, RECIPE_2_SUNSET_BUTTON_A, RECIPE_2_SUNSET_BUTTON_B,
  RECIPE_2_FLOW_D_0, RECIPE_2_FLOW_D_1, RECIPE_2_FLOW_D_BUTTON_A, RECIPE_2_FLOW_D_BUTTON_B,
  RECIPE_2_NOFLOW_D_0, RECIPE_2_NOFLOW_D_1, RECIPE_2_NOFLOW_D_BUTTON_A, RECIPE_2_NOFLOW_D_BUTTON_B,
  RECIPE_2_FLOW_N_0, RECIPE_2_FLOW_N_1, RECIPE_2_FLOW_N_BUTTON_A, RECIPE_2_FLOW_N_BUTTON_B,
  RECIPE_2_NOFLOW_N_0, RECIPE_2_NOFLOW_N_1, RECIPE_2_NOFLOW_N_BUTTON_A, RECIPE_2_NOFLOW_N_BUTTON_B,
  RECIPE_2_EC_H_0, RECIPE_2_EC_H_1, RECIPE_2_EC_H_BUTTON_A, RECIPE_2_EC_H_BUTTON_B,
  RECIPE_2_EC_L_0, RECIPE_2_EC_L_1, RECIPE_2_EC_L_BUTTON_A, RECIPE_2_EC_L_BUTTON_B,  
  RECIPE_2_PH_H_0, RECIPE_2_PH_H_1, RECIPE_2_PH_H_BUTTON_A, RECIPE_2_PH_H_BUTTON_B,
  RECIPE_2_PH_L_0, RECIPE_2_PH_L_1, RECIPE_2_PH_L_BUTTON_A, RECIPE_2_PH_L_BUTTON_B,
  RECIPE_2_END,
  
  SYS_CLOCK_0, SYS_CLOCK_1, SYS_CLOCK_BUTTON_A, SYS_CLOCK_BUTTON_B,
  SYS_CONTRAST_0, SYS_CONTRAST_1, SYS_CONTRAST_BUTTON_A, SYS_CONTRAST_BUTTON_B,
  SYS_PASS_OP1_0, SYS_PASS_OP1_1, SYS_PASS_OP1_BUTTON_A, SYS_PASS_OP1_BUTTON_B,
  SYS_PASS_OP2_0, SYS_PASS_OP2_1, SYS_PASS_OP2_BUTTON_A, SYS_PASS_OP2_BUTTON_B,
  SYS_PASS_SUP1_0, SYS_PASS_SUP1_1, SYS_PASS_SUP1_BUTTON_A, SYS_PASS_SUP1_BUTTON_B,
  SYS_PASS_SUP2_0, SYS_PASS_SUP2_1, SYS_PASS_SUP2_BUTTON_A, SYS_PASS_SUP2_BUTTON_B,
  SYS_ERASE_SD_0, SYS_ERASE_SD_BUTTON_A, SYS_ERASE_SD_BUTTON_B,
  SYS_END,
  
};


#endif  /* __UI_H__  */